version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      server:
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    networks:
      server:
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
      - 2888
      - 3888
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      server:
  gate1:
    image: com.twh/game-gate:1.0-SNAPSHOT
    restart: always
    hostname: gate1
    container_name: gate1
    ports:
      - 9001:9000
    environment:
      NETTY_SERVER_ADDRESS: gate1
    networks:
      server:
  room1:
    image: com.twh/game-room:1.0-SNAPSHOT
    restart: always
    hostname: room1
    container_name: room1
    ports:
      - 9002:9000
    environment:
      NETTY_SERVER_ADDRESS: room1
    networks:
      server:
networks:
  server:
    driver: bridge