zookeeper:
  connection: zoo1:2181,zoo2:2181,zoo3:2181
  root-path: /game-server

netty:
  server:
    ssl: false
    port: 9000
    channel: io.netty.channel.epoll.EpollServerSocketChannel
    boss-group:
      event-loop-group: io.netty.channel.epoll.EpollEventLoopGroup
    work-group:
      event-loop-group: io.netty.channel.epoll.EpollEventLoopGroup
    block-group:
      event-loop-group: io.netty.channel.epoll.EpollEventLoopGroup
      threads: 200
  socket:
    keepalive: true
    backlog: 1024
    autoRead: false