zookeeper:
  connection: zoo1:2181,zoo2:2182,zoo3:2183
  root-path: /game-server

netty:
  server:
    name: room-server
    server-type: MATCH
    ssl: false
    port: 7777
    channel: io.netty.channel.socket.nio.NioServerSocketChannel
    boss-group:
      eventLoopGroup: io.netty.channel.nio.NioEventLoopGroup
    socket:
      keepalive: true
      backlog: 1024
